export const GET_GAMES = 'GET_GAMES'
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE'
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS'

export const GET_RACES = 'GET_RACES'
export const GET_RACES_FAILURE = 'GET_RACES_FAILURE'
export const GET_RACES_SUCCESS = 'GET_RACES_SUCCESS'
